name: Deploy PRODUCTION Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Run Prisma Migrate (Deploy)
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

      - name: Run Prisma Generate
        run: npx prisma generate
